/* divconst.h -- division by a compile-time constant, without dividing.
 *
 * PURE C, no hardware. Read docs/optimisation.md before changing anything in
 * here, and never change it without running test_divconst.
 *
 * WHY THIS EXISTS. A 32-bit division costs 1,026 cycles on this part -- 257 us
 * -- because XC8 calls ___lldiv, which is a loop of one iteration per bit of
 * the divisor. The core divides by a constant in ten places, and
 * txframes_gather is nine of them in a row.
 *
 * THE TRICK, AND WHY IT IS NOT THE USUAL ONE. Dividing by a constant d is
 * normally replaced by multiplying by a fixed-point reciprocal and shifting.
 * On this compiler that is a trap: XC8 v4.00 calls ___lmul for any multiply
 * wider than 8 bits, and ___lmul is also a per-bit loop, so the obvious
 * rewrite is no faster than the division it replaces.
 *
 * What XC8 *does* compile to the hardware multiplier is uint8 x uint8, and
 * uint16 x uint8 -- one MULWF each, no call. So mulhi_u32() below builds the
 * 64-bit product out of sixteen byte products and keeps the top half. It comes
 * out as 265 instructions of straight-line code with no branches and no calls,
 * against roughly 1,050 cycles for the division. About 3.5x, and the whole of
 * it is in how the multiply is spelled.
 *
 * HOW THE CONSTANTS ARE CHOSEN. For divisor d, pick a shift s and
 * m = ceil(2^(32+s) / d); then x/d == (x*m >> 32) >> s for every x in range.
 * tools/divconst.py derives them and test_divconst.c proves them -- exhaustively
 * where the range allows it and against every boundary where it does not. Do
 * not add a divisor here by hand.
 */
#ifndef DIVCONST_H
#define DIVCONST_H

#include <stdint.h>

/* The high 32 bits of x * m. Straight-line, sixteen byte products.
 *
 * Every multiply below is written (uint16_t)a * b with both operands uint8_t,
 * which is the exact shape XC8 turns into MULWF. Widening either operand puts
 * ___lmul back and undoes the entire point of this file. */
static uint32_t mulhi_u32(uint32_t x, uint32_t m)
{
    uint8_t x0 = (uint8_t)x, x1 = (uint8_t)(x >> 8);
    uint8_t x2 = (uint8_t)(x >> 16), x3 = (uint8_t)(x >> 24);
    uint8_t m0 = (uint8_t)m, m1 = (uint8_t)(m >> 8);
    uint8_t m2 = (uint8_t)(m >> 16), m3 = (uint8_t)(m >> 24);
    uint32_t carry, acc;

    uint32_t p0 = (uint32_t)((uint16_t)x0 * m0);
    uint32_t p1 = (uint32_t)((uint16_t)x0 * m1)
                + (uint32_t)((uint16_t)x1 * m0);
    uint32_t p2 = (uint32_t)((uint16_t)x0 * m2)
                + (uint32_t)((uint16_t)x1 * m1)
                + (uint32_t)((uint16_t)x2 * m0);
    uint32_t p3 = (uint32_t)((uint16_t)x0 * m3)
                + (uint32_t)((uint16_t)x1 * m2)
                + (uint32_t)((uint16_t)x2 * m1)
                + (uint32_t)((uint16_t)x3 * m0);
    uint32_t p4 = (uint32_t)((uint16_t)x1 * m3)
                + (uint32_t)((uint16_t)x2 * m2)
                + (uint32_t)((uint16_t)x3 * m1);
    uint32_t p5 = (uint32_t)((uint16_t)x2 * m3)
                + (uint32_t)((uint16_t)x3 * m2);
    uint32_t p6 = (uint32_t)((uint16_t)x3 * m3);

    /* Propagate byte by byte through the low half, keeping only the carry --
     * the low 32 bits of the product are discarded by definition. */
    carry = (p0 >> 8) + p1;
    carry = (carry >> 8) + p2;
    carry = (carry >> 8) + p3;

    acc  = (carry >> 8) + p4;
    acc += p5 << 8;
    acc += p6 << 16;
    return acc;
}

/* Generated by tools/divconst.py; proved by test/test_divconst.c. Each entry is
 * (magic, shift) for the divisor named.
 *
 * A SHIFT OF 8, 16 OR 24 IS FREE and any other shift is a loop -- XC8 emits
 * single-bit rotates with a counter even when the count is a constant. So
 * divconst.py prefers a multiple of eight, which needs 2**s < d and is
 * therefore available to 1000 and 95500 but not to 10, 100 or 120. Their
 * shifts are 3, 5 and 6, so their loops are short; 3600 and 10000 keep 11 and
 * 13 because no multiple of eight is exact for them inside 32 bits. */
#define DIVC_10         0xCCCCCCCDul, 3u
#define DIVC_100        0x51EB851Ful, 5u
#define DIVC_120        0x88888889ul, 6u
#define DIVC_1000       0x4189374Cul, 8u
#define DIVC_3600       0x91A2B3C5ul, 11u
#define DIVC_10000      0xD1B71759ul, 13u
/* 95500 is the one with a declared range: over the full 32 bits its magic
 * needs 33 bits and would not fit. torque_d * 10 * rpm stays under 2**30 --
 * tools/divconst.py carries the arithmetic. */
#define DIVC_95500      0xAFAD7AC4ul, 16u

/* x / d, for the divisors above only. Use as div_const(x, DIVC_1000).
 *
 * MACROS, NOT FUNCTIONS, AND THAT IS THE POINT. Written as a function taking
 * the shift as a parameter, XC8 cannot know the shift at compile time and
 * emits a *loop* of single-bit shifts -- which put back most of what the
 * reciprocal had just saved. As a macro the shift is a literal at every call
 * site and becomes a fixed sequence of byte moves.
 *
 * DIVC_1000 expands to two arguments, "magic, shift". The preprocessor counts
 * a macro's arguments BEFORE expanding them, so div_const(x, DIVC_1000) is a
 * two-argument call and has to hand off to div_const_(), which sees three
 * after the expansion is rescanned. That indirection is why there are two
 * names, and removing it gives "too few arguments" at every call site.
 *
 * Each argument is used exactly once, so there is nothing to evaluate twice. */
#define div_const(x, mp)                div_const_(x, mp)
#define div_const_(x, magic, shift)     (mulhi_u32((x), (magic)) >> (shift))

/* (x + d/2) / d -- the rounding form the core uses everywhere. The addition
 * cannot overflow for any value this firmware produces; test_divconst.c pins
 * the boundary for each divisor. */
#define div_const_round(x, half, mp)    div_const_round_(x, half, mp)
#define div_const_round_(x, half, magic, shift)     div_const_((uint32_t)(x) + (uint32_t)(half), (magic), (shift))

#endif /* DIVCONST_H */
